# Generated by Django 6.0.5 on 2026-06-06 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    def gen_unique_uuids(apps, schema_editor):
        TimeLog = apps.get_model('timetracking', 'TimeLog')
        for row in TimeLog.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=['uuid'])

    dependencies = [
        ("timetracking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelog",
            name="id",
        ),
        migrations.AddField(
            model_name="timelog",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.RunPython(gen_unique_uuids, elidable=True),
    ]
