# Generated by Django 6.0.5 on 2026-06-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetracking", "0002_remove_timelog_id_timelog_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timelog",
            old_name="uuid",
            new_name="id",
        ),
    ]
