# Generated by Django 6.0.5 on 2026-05-31 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("color", models.CharField(default="#D1D5DB", max_length=7)),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="teams.team"
                    ),
                ),
            ],
        ),
    ]
