# Generated by Django 6.0.5 on 2026-05-31 13:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerContract",
            fields=[
                (
                    "contract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contracts.contract",
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "employment_type",
                    models.IntegerField(
                        choices=[
                            (4, "Part-time (4 Hours)"),
                            (5, "Part-time (5 Hours)"),
                            (6, "Part-time (6 Hours)"),
                            (7, "Part-time (7 Hours)"),
                            (8, "Full-time (8 Hours)"),
                        ],
                        default=8,
                        help_text="Designated daily contractual obligation commitment hours.",
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
            ],
            bases=("contracts.contract",),
        ),
        migrations.CreateModel(
            name="FreelancerContract",
            fields=[
                (
                    "contract_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contracts.contract",
                    ),
                ),
                (
                    "hourly_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("daily_hours_required", models.PositiveIntegerField()),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="contracts/freelancers/"
                    ),
                ),
            ],
            bases=("contracts.contract",),
        ),
    ]
