# Generated by Django 6.0.5 on 2026-06-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_terminated",
            field=models.BooleanField(default=False),
        ),
    ]
