# Generated by Django 6.0.5 on 2026-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_is_terminated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancercontract",
            name="document_file",
            field=models.FileField(
                blank=True, null=True, upload_to="freelancer_contract/"
            ),
        ),
    ]
