# Generated by Django 6.0.5 on 2026-06-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_freelancercontract_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancercontract",
            name="document_file",
            field=models.FileField(
                blank=True, null=True, upload_to="freelancer_contracts/"
            ),
        ),
    ]
