# Generated by Django 6.0.5 on 2026-06-15 04:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_alter_freelancercontract_document_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"verbose_name": "contract", "verbose_name_plural": "contracts"},
        ),
        migrations.AlterModelOptions(
            name="employercontract",
            options={
                "verbose_name": "employer contract",
                "verbose_name_plural": "employer contracts",
            },
        ),
        migrations.AlterModelOptions(
            name="freelancercontract",
            options={
                "verbose_name": "freelancer contract",
                "verbose_name_plural": "freelancer contracts",
            },
        ),
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="is_terminated",
            field=models.BooleanField(default=False, verbose_name="is terminated"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="role_title",
            field=models.CharField(max_length=255, verbose_name="role title"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="employercontract",
            name="employment_type",
            field=models.IntegerField(
                choices=[
                    (4, "Part-time (4 Hours)"),
                    (5, "Part-time (5 Hours)"),
                    (6, "Part-time (6 Hours)"),
                    (7, "Part-time (7 Hours)"),
                    (8, "Full-time (8 Hours)"),
                ],
                default=8,
                help_text="Designated daily contractual obligation commitment hours.",
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(8),
                ],
                verbose_name="employment type",
            ),
        ),
        migrations.AlterField(
            model_name="employercontract",
            name="monthly_payment",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="monthly payment"
            ),
        ),
        migrations.AlterField(
            model_name="freelancercontract",
            name="daily_hours_required",
            field=models.PositiveIntegerField(verbose_name="daily hours required"),
        ),
        migrations.AlterField(
            model_name="freelancercontract",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="freelancer_contracts/",
                verbose_name="document file",
            ),
        ),
        migrations.AlterField(
            model_name="freelancercontract",
            name="hourly_payment",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="hourly payment"
            ),
        ),
    ]
